### ISSUE TITLE
Default Building Settings breaks solid oxidizer tanks

### ISSUE THREAD

**Issue by DarkDaskin** [AzeTheGreat/ONI-Mods#12]
I was playing the latest stable Spaced Out release (EX1 57-452873-D). I had Sweep Only by default enabled in the mod settings. When I built a small solid oxidizer tank, neither dupes or auto-sweeper would fill it. It turned out the tank had Sweep Only enabled, but this setting is invisible, so it caused a lot of confusion. The only way to fix it is to change the mod setting, reload the game and rebuild the tank.
The mod should only change the setting for buildings which have corresponding UI to toggle it.

**Comment by AzeTheGreat** [comment]
Thank you for the report, this has been fixed in https://github.com/AzeTheGreat/ONI-Mods/commit/abbb18062946d1a24473519f90d5477ac9596dd8.
