### ISSUE TITLE
Better Info Cards: grouping not working properly

### ISSUE THREAD

**Issue by DefectiveNu** [AzeTheGreat/ONI-Mods#13]
Temperature grouping seems to not work properly
I have the temperature bandwidth set to 1000, but they only seem to group when the temps match exactly in normal overlay

I've disabled mods which I think could change info cards (thermal tool tips, display all temps) which doesn't change the behavior.

Interestingly, the thermal overlay works better whether thermal tool tips is on or off (default config where it only adds info in the thermal overlay. thought this might be causing the issue but it seems to not affect it).  The grouping seems to activate better but still doesn't capture everything it should, it seems to only group piles that are the exact same quantity

Base game, have the dlc purchased but turned off.  Critters still get grouped fine 

![20210429233909_1](https://user-images.githubusercontent.com/27719173/116645601-2b0bdc80-a944-11eb-8635-a0a38fac2ab2.jpg)
![20210429233923_1](https://user-images.githubusercontent.com/27719173/116645605-2b0bdc80-a944-11eb-90a7-83801fc9eea1.jpg)

**Comment by AzeTheGreat** [comment]
Thank you for the report!  I apologize for the lengthy delay on fixing this issue.

Info card grouping has been fixed in https://github.com/AzeTheGreat/ONI-Mods/commit/c768efb8cb21ac38f8e82f06599938f4111b9617 and released on Steam.

Let me know if you encounter any further issues!
