### ISSUE TITLE
Go crash game due to Better info card

### ISSUE THREAD

**Issue by Uzumaki-Boruto** [AzeTheGreat/ONI-Mods#16]
Here is my player log
[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/6984160/Player.log)

**Comment by AzeTheGreat** [comment]
Can you reproduce this issue?

**Comment by Uzumaki-Boruto** [comment]
I remember that I'm cleaning slime with highest priority

**Comment by AzeTheGreat** [comment]
Thank you.  I believe this should finally be fixed with 123a3d6077c4b38be2ba0eee2b8b827410d6d7e1.

**Comment by Uzumaki-Boruto** [comment]
Thank you for your work.
