### ISSUE TITLE
Crash when I click on a conveyor loader

### ISSUE THREAD

**Issue by Maelztrom** [AzeTheGreat/ONI-Mods#19]
ArgumentException: An item with the same key has already been added. Key: Breathable

System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <695d1cc93cca45069c528c15c9fdd749>:0)
TreeFilterableSideScreen.AddRow (Tag rowTag) (at <33cbadb4d53344698461e1b8bda03e57>:0)
TreeFilterableSideScreen.CreateCategories () (at <33cbadb4d53344698461e1b8bda03e57>:0)
TreeFilterableSideScreen.SetTarget (UnityEngine.GameObject target) (at <33cbadb4d53344698461e1b8bda03e57>:0)
DetailsScreen.<Refresh>b__40_0 (DetailsScreen+SideScreenRef scn) (at <33cbadb4d53344698461e1b8bda03e57>:0)
System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) (at <695d1cc93cca45069c528c15c9fdd749>:0)
DetailsScreen.Refresh (UnityEngine.GameObject go) (at <33cbadb4d53344698461e1b8bda03e57>:0)
RootMenu.OnSelectObject (System.Object data) (at <33cbadb4d53344698461e1b8bda03e57>:0)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KMonoBehaviour.Trigger (System.Int32 hash, System.Object data) (at <53ba8544b0394db88dcaac034e1fe553>:0)
(wrapper dynamic-method) SelectTool.SelectTool.Select_Patch1(SelectTool,KSelectable,bool)
SelectTool.OnLeftClickDown (UnityEngine.Vector3 cursor_pos) (at <33cbadb4d53344698461e1b8bda03e57>:0)
PlayerController.OnKeyDown (KButtonEvent e) (at <33cbadb4d53344698461e1b8bda03e57>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputHandler.HandleEvent (KInputEvent e) (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputController.Dispatch () (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputManager.Dispatch () (at <53ba8544b0394db88dcaac034e1fe553>:0)
KInputManager.Update () (at <53ba8544b0394db88dcaac034e1fe553>:0)
GameInputManager.Update () (at <53ba8544b0394db88dcaac034e1fe553>:0)
Global.Update () (at <33cbadb4d53344698461e1b8bda03e57>:0)

Build: U41-498381-S

I think it's a conflict with 'customize buildings', the crash stopped when i disabled that mod.

**Comment by AzeTheGreat** [comment]
Hi, I know this is a late response, but I've not been able to replicate this issue.  If you have any more information, or if you can still replicate it, please open another issue.  It would be helpful to include a full log if you do so.
