### ISSUE TITLE
NRE in BetterLogicOverlay

### ISSUE THREAD

**Issue by TheMule71** [AzeTheGreat/ONI-Mods#2]
Hello there! First let me thank you for your great QoL mods.

I have an issue with the Better Automation Overlay (I believe). Here's the exception I get:

> [10:39:11.666] [1] [INFO] Error occurred with mods active. Disabling all mods (unless dev mods active).
> NullReferenceException: Object reference not set to an instance of an object
>   at BetterLogicOverlay.Extensions.GetAbbreviation (Element element) [0x00000] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.LogicSettingDisplay.ConduitElementSensorSetting.GetSetting () [0x00010] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.LogicSettingUIInfo.UpdateText () [0x0000e] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.GateSettingDisplay.OnUpdateUI () [0x0001a] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.GateSettingDisplay+UpdateUI.Postfix () [0x00000] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at (wrapper dynamic-method) OverlayModes+Logic.UpdateUI_Patch1(object)
>   at OverlayModes+Logic.Update () [0x00990] in <62de69961f464b72923c510914d6557e>:0 
>   at OverlayScreen.LateUpdate () [0x00000] in <62de69961f464b72923c510914d6557e>:0 
>  
> (Filename: <8aff9a85111748d8ba77255c30ac2322> Line: 0)

Complete output_log.txt attached.

[output_log.txt](https://github.com/AzeTheGreat/ONI-Mods/files/4301702/output_log.txt)

**Comment by AzeTheGreat** [comment]
Yup, I’ve already fixed this and I’ll be releasing an update some time today.  Thank you for the report though.

**Comment by takumiabe** [comment]
Thank you great mod!
I use Better Automation Overlay too.

but I encounted simular errors like this:

> [11:44:09.980] [1] [INFO] Error occurred with mods active. Disabling all mods (unless dev mods active).
> NullReferenceException: Object reference not set to an instance of an object
>   at BetterLogicOverlay.Extensions.GetAbbreviation (Element element) [0x00000] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.LogicSettingDisplay.ConduitElementSensorSetting.GetSetting () [0x00010] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.LogicSettingUIInfo.UpdateText () [0x0000e] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.GateSettingDisplay.OnUpdateUI () [0x0001a] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.GateSettingDisplay+UpdateUI.Postfix () [0x00000] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at (wrapper dynamic-method) OverlayModes+Logic.UpdateUI_Patch1(object)
>   at OverlayModes+Logic.Update () [0x00990] in <76bf6a41bfb64def9b51dda67e8b0011>:0 
>   at OverlayScreen.LateUpdate () [0x00000] in <76bf6a41bfb64def9b51dda67e8b0011>:0 
>  
> (Filename: <8aff9a85111748d8ba77255c30ac2322> Line: 0)
> 

Is this same error?

thanks!
