### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by ElectronicsArchiver** [AzeTheGreat/ONI-Mods#20]
<br>
<br>

<div align = center>

I've found that multiple GitHub ONI mod repositories 
were describing how to manually install mods, 
so I made a guide instead.

[Installation Guide]

Would you mind if I made a PR, replacing 
the two sentences with a link to the guide?

</div>

<br>
<br>

[Installation Guide]: https://github.com/OpenModding/Installation/tree/main/Games/Oxygen%20Not%20Included

**Comment by AzeTheGreat** [comment]
I appreciate the effort, but I don't think that's necessary.
