### ISSUE TITLE
Some missing sensor settings

### ISSUE THREAD

**Issue by zivvel** [AzeTheGreat/ONI-Mods#23]
I have a hydro sensor that overlaps the corner of a memory toggle, and the hydro sensor setting doesn't show in the overlay.
![hydro-missing-sensor-setting](https://user-images.githubusercontent.com/242258/197337218-5f2782f1-c8c2-499c-b096-4f945feda327.png)

**Comment by AzeTheGreat** [comment]
Thank you for the report.  This is fixed in 4728395314d242492d527f44d0323195281aa61f and the mod has been updated.
