### ISSUE TITLE
Better Info Cards Crashing

### ISSUE THREAD

**Issue by DisciplesOfChaos** [AzeTheGreat/ONI-Mods#25]
While playing suddenly, without apparent cause, it crashed.
First time reporting bugs on github, Please inform Us of any mistakes We might make.
Thank you,
  The Disciples
Player Log:
KeyNotFoundException: The given key was not present in the dictionary.

System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <695d1cc93cca45069c528c15c9fdd749>:0)
BetterInfoCards.TextInfo`1+<>c__DisplayClass11_0[T].<GetSplitByRange>g__GetTIValue|4 (BetterInfoCards.InfoCard ic) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.TextInfo`1+<>c__DisplayClass11_0[T].<GetSplitByRange>b__0 (BetterInfoCards.InfoCard x) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].MoveNext () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source, System.Int32& length) (at <0463b2ef957545c0a51b42f372cd4fbb>:0)
System.Collections.Generic.SortedSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection, System.Collections.Generic.IComparer`1[T] comparer) (at <0463b2ef957545c0a51b42f372cd4fbb>:0)
System.Collections.Generic.SortedSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) (at <0463b2ef957545c0a51b42f372cd4fbb>:0)
BetterInfoCards.TextInfo`1[T].GetSplitByRange (System.Collections.Generic.List`1[T] cards, System.ValueTuple`2[T1,T2] def) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.TextInfo`1[T].<SplitByTIDefs>b__10_0 (System.Collections.Generic.List`1[T] g, System.ValueTuple`2[T1,T2] def) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.Util.Splitters+<>c__DisplayClass3_1`2[TVal,TSplit].<SplitBySplitters>b__0 (System.Collections.Generic.List`1[T] x) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.Util.Splitters.SplitBySplitters[TVal,TSplit] (System.Collections.Generic.List`1[T] source, System.Collections.Generic.List`1[T] splitters, System.Func`3[T1,T2,TResult] getSplits) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.TextInfo`1[T].SplitByTIDefs (System.Collections.Generic.List`1[T] cards) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.DisplayCards+<>c.<UpdateData>b__0_5 (System.Collections.Generic.List`1[T] group, System.Collections.Generic.KeyValuePair`2[TKey,TValue] ti) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.Util.Splitters+<>c__DisplayClass3_1`2[TVal,TSplit].<SplitBySplitters>b__0 (System.Collections.Generic.List`1[T] x) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.Util.Splitters.SplitBySplitters[TVal,TSplit] (System.Collections.Generic.List`1[T] source, System.Collections.Generic.List`1[T] splitters, System.Func`3[T1,T2,TResult] getSplits) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.DisplayCards+<>c.<UpdateData>b__0_2 (System.Collections.Generic.List`1[T] cards) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.Util.Splitters.SplitMany[T] (System.Collections.Generic.List`1[T] source, System.Func`2[T,TResult] getSplits) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.DisplayCards.UpdateData (System.Collections.Generic.List`1[T] infoCards) (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
BetterInfoCards.ProcessHoverInfo.Prefix () (at <73a3ed1bcf054ea2bdd5844646c541c9>:0)
(wrapper dynamic-method) HoverTextDrawer.HoverTextDrawer.EndDrawing_Patch1(HoverTextDrawer)
(wrapper dynamic-method) SelectToolHoverTextCard.SelectToolHoverTextCard.UpdateHoverElements_Patch0(SelectToolHoverTextCard,System.Collections.Generic.List`1<KSelectable>)
InterfaceTool.UpdateHoverElements (System.Collections.Generic.List`1[T] hits) (at <d13cbb0b55a94ef09bb55c2436a6b8ee>:0)
InterfaceTool.LateUpdate () (at <d13cbb0b55a94ef09bb55c2436a6b8ee>:0)

Build: U44-535842-V

**Comment by AzeTheGreat** [comment]
Please provide the full log.  `C:\Users\%username%\AppData\LocalLow\Klei\Oxygen Not Included\Player.log`.

This shouldn't be possible unless you're on a nearly year old version.

**Comment by AzeTheGreat** [comment]
I'm going to close this since no log has been provided.  I am 98% sure that you are on a very outdated version.  If you can provide a log I will take a more in depth look.
