### ISSUE TITLE
Could not find GameplayEvent (Better Info Cards Mods)

### ISSUE THREAD

**Issue by dosontung** [AzeTheGreat/ONI-Mods#29]
Hi! The mod seems to crash the game when I click on meteor detail in space map

I run game in latest version on steam. 

Thanks

[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/11242365/Player.log)

**Comment by AzeTheGreat** [comment]
Can you reproduce this crash?  If so, could you please provide more detail.  I tried clicking on every planet/asteroid in the starmap and didn't have any issues.

**Comment by dosontung** [comment]
I capture image for this bugs. 
I am not sure about this bugs, I've tried to disabled all mods but it's still remain. 
![image](https://user-images.githubusercontent.com/39339626/232325091-050df322-0dfa-4b5c-983c-b0dd2000eac9.png)

This is my save game: (remove tail .txt)
[Không gian Hầm trú ẩn.sav.txt](https://github.com/AzeTheGreat/ONI-Mods/files/11242746/Khong.gian.H.m.tru.n.sav.txt)

**Comment by AzeTheGreat** [comment]
If it happens without any mods enabled, then it's not a BIC problem.  Looks like something has messed up your save file.  This could be due to a broken world gen mod, a removed content mod, or just a vanilla issue.
