### ISSUE TITLE
Suppress Notifications - Localization

### ISSUE THREAD

**Issue by DarkEviL88** [AzeTheGreat/ONI-Mods#32]
It would be nice to be able to localize into another language

**Comment by AzeTheGreat** [comment]
Are you asking to translate the mod yourself, or just wishing that it was translated for your use?

My mods support localization, I've just never had anyone offer to help.

**Comment by DarkEviL88** [comment]
I just want to help with the translation. I have several of your mods installed and would like to translate them all if possible. I'll share the translation with you if you tell me where to get the templates.

**Comment by DarkEviL88** [comment]
Better Automation Overlay, seconds and grams

**Comment by AzeTheGreat** [comment]
Took a while to get around to this.  Localization has been enabled for Suppress Notifications in 5ce0e19.

If you'd still like to translate, I just need the strings in [this file](https://github.com/AzeTheGreat/ONI-Mods/blob/master/src/SuppressNotifications/Util/STRINGS.cs) translated.  The rest of my mods will have the strings to be translated in the same file.

Better Automation Overlay shouldn't need those units translated - they're just pulled from the game's units.  Could you let me know where you're seeing untranslated units in a separate issue?

I'll close this issue out as localization support is enabled.  Please open a new issue to to provide translations.

**Comment by DarkEviL88** [comment]
I'm not a coder and don't understand anything about VS. I usually translate using templates (.po) provided by mod authors.
