### ISSUE TITLE
Better Info Cards - KeyNotFound Crash

### ISSUE THREAD

**Issue by BrotherMatthew** [AzeTheGreat/ONI-Mods#34]
I don't have much to report, the crash was somewhat unpredictable, but I thought the logs might be helpful.
I my mods (info cards and thermal tooltips) were up to date I checked as instructed.
I've attached the crash logs from the in-game crash reporter, as well as from the debug console mod.

[ONI Crash Logs 20 07 2023.txt](https://github.com/AzeTheGreat/ONI-Mods/files/12104841/ONI.Crash.Logs.20.07.2023.txt)
[ONI Red Text From Debug Mod.txt](https://github.com/AzeTheGreat/ONI-Mods/files/12104842/ONI.Red.Text.From.Debug.Mod.txt)

**Comment by BrotherMatthew** [comment]
Happened again, I believe it's a similar crashing issue
I'll dump the crash logs here again in case they are helpful.
Love the mod btw thank you :)
[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/12136306/Player.log)

[ONI Crash Logs 22 07 2023.txt](https://github.com/AzeTheGreat/ONI-Mods/files/12136310/ONI.Crash.Logs.22.07.2023.txt)

[ONI Red Text From Debug Mod22 07 2023.txt](https://github.com/AzeTheGreat/ONI-Mods/files/12136311/ONI.Red.Text.From.Debug.Mod22.07.2023.txt)

**Comment by AzeTheGreat** [comment]
Have you noticed any patterns about where it's occurring?  If not, I might need to provide a custom build with extra logging.

**Comment by AzeTheGreat** [comment]
I've added some extra logging (28e0f7fa0086443ded043c9627a7b40e3d5ba9f1) to hopefully narrow down this issue in the latest release.  If you encounter this crash again, please upload your full log; hopefully that will provide enough info to finally fix it.

**Comment by Phstarfish** [comment]
This crash has happened several times.And I don't why it take place.
I am really fond of your mod & thanks you :)
[crash.txt](https://github.com/AzeTheGreat/ONI-Mods/files/13975547/crash.txt)

**Comment by AzeTheGreat** [comment]
@Phstarfish Thanks for the report.  Could you please double check that crash log?  It's an empty file.

If you're getting this issue consistently, try to keep an eye out for any patterns that trigger it.  Also, your save to go along with the crash log would be helpful.

**Comment by Phstarfish** [comment]
@AzeTheGreat  Sorry for posting the wrong file...
The crash happened again, and I find it often happened when I am sweeping a lot of stuff off the ground...
Thanks for your reply and contributions for the mod :)
[crash.txt](https://github.com/AzeTheGreat/ONI-Mods/files/13992773/crash.txt)
[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/13992776/Player.log)
