### ISSUE TITLE
Better Info Card KeyNotFound Crash

### ISSUE THREAD

**Issue by Alex1476** [AzeTheGreat/ONI-Mods#35]
[output_log.txt](https://github.com/AzeTheGreat/ONI-Mods/files/12409123/output_log.txt)
[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/12409124/Player.log)
I dug out an entire planetoid (The water one) and i beleive i hover over a tile and it crashed. This has happened on my previous excavation ventures.

**Comment by AzeTheGreat** [comment]
I'm closing this as a duplicate of #34.  If you get any additional info or have reproducible crashes, please leave a comment there for further testing.  This one is hard to pin down.
