### ISSUE TITLE
Better info card not compatible with Fast Track mod

### ISSUE THREAD

**Issue by VitaminC603** [AzeTheGreat/ONI-Mods#36]
When enabled with fast track mod, player cannot switch between overlaping objects and buildings in a single block by repeatedly clicking on them.  Disabling either Fast Track or Better Info Card fixes this problem

**Comment by AzeTheGreat** [comment]
I'm not able to reproduce this.  Is it with all objects/buildings?  Everything I'm testing is working as expected.

**Comment by AzeTheGreat** [comment]
Without additional details, I'm going to close this.  Fast Track touches a lot of code and I'm going to assume it was temporarily partially broken - all of my testing appears to work  fine.   If you have more details, feel free to leave a comment.
