### ISSUE TITLE
No Research Alerts - doesn't work at 2023.11.23

### ISSUE THREAD

**Issue by eleroy5** [AzeTheGreat/ONI-Mods#37]
Version of mod 2023.3.6.1
ONI updated with Packed snacks update
I have the alert notification for the 4 types of research

**Comment by AzeTheGreat** [comment]
Are you talking about the notification (top left, with "Long Commutes") or the new item badge on the build menu categories?

I just tested and everything seems to work fine.  Keep in mind that to disable the notification there's a separate checkbox in the mod options.

**Comment by AzeTheGreat** [comment]
I am closing this since I've tested it as working and I've not received further information.  If you do have more information, please open a new issue with it.
