### ISSUE TITLE
Suppress Notifications - Translation

### ISSUE THREAD

**Issue by DarkEviL88** [AzeTheGreat/ONI-Mods#38]
I translated the strings in your file.
[STRINGS.zip](https://github.com/AzeTheGreat/ONI-Mods/files/13462416/STRINGS.zip)

**Comment by AzeTheGreat** [comment]
Thank you!

I have implemented this translation in 6426165ece95d601e66d022006c993ef2d68dcd2 and released Suppress Notifications with it in 96180af3f206caa4bac812dd17329d77ec295ae3.  This is available on Steam now.

I've made an effort to make translating _much_ simpler.  Please see [Translating.md](https://github.com/AzeTheGreat/ONI-Mods/blob/master/Translations/TRANSLATING.md) for a complete guide.

**Comment by DarkEviL88** [comment]
[ru.zip](https://github.com/AzeTheGreat/ONI-Mods/files/14126943/ru.zip)
I have revised my translation of your mod and changed it to be more understandable for players.

**Comment by AzeTheGreat** [comment]
Thanks.  Implemented in 17f0c14889667ef82a78e451beae157eb07a18b5.  This will be rolled into the next release of Suppress Notifications.
