### ISSUE TITLE
"Better Info Cards" seems to crash if "Show Industrial Machinery Tag" is present

### ISSUE THREAD

**Issue by DenisNoobOnLine** [AzeTheGreat/ONI-Mods#39]
Hi and thx for your usefull mod (for me to be integrated in the original game).
I noticed that your mod seems to systematically crash when installed with the mod "Show Industrial Machinery Tag".
I attach the requested "Player.log" file  the the information generated by the game when the crash occures. I hope you'll be abble to have  a solution to this issue.  Let me know if I have to contact the other mod developper or not.
Again thx for your work on ONI
Denis

[Player.log](https://github.com/AzeTheGreat/ONI-Mods/files/13787020/Player.log)

[Game info when the game crashes.txt](https://github.com/AzeTheGreat/ONI-Mods/files/13787019/Game.info.when.the.game.crashes.txt)

**Comment by AzeTheGreat** [comment]
Thanks for the report.  However, this is actually a crash in Show Industrial Machinery Tag's method.  Better Info Cards is only mentioned because I have a path much earlier in the call stack.  Please leave a comment on [this open issue](https://github.com/Cairath/ONI-Mods/issues/178).

**Comment by DenisNoobOnLine** [comment]
Hi, Thx for your quick answer and your analysis of the issue that I was unnabble to do. If so, I will inform the developper of the  "Show Industrial Machinery Tag" mod in order to ask him if it'd possible to fix his own mod. Again thx. Have a good end of year and a futur happy new year ;)
