### ISSUE TITLE
NRE in Better Automation Overlay

### ISSUE THREAD

**Issue by AzeTheGreat** [AzeTheGreat/ONI-Mods#4]
Thank you great mod!
I use Better Automation Overlay too.

but I encounted simular errors like this:

> [11:44:09.980] [1] [INFO] Error occurred with mods active. Disabling all mods (unless dev mods active).
> NullReferenceException: Object reference not set to an instance of an object
>   at BetterLogicOverlay.Extensions.GetAbbreviation (Element element) [0x00000] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.LogicSettingDisplay.ConduitElementSensorSetting.GetSetting () [0x00010] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.LogicSettingUIInfo.UpdateText () [0x0000e] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.GateSettingDisplay.OnUpdateUI () [0x0001a] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at BetterLogicOverlay.GateSettingDisplay+UpdateUI.Postfix () [0x00000] in <8aff9a85111748d8ba77255c30ac2322>:0 
>   at (wrapper dynamic-method) OverlayModes+Logic.UpdateUI_Patch1(object)
>   at OverlayModes+Logic.Update () [0x00990] in <76bf6a41bfb64def9b51dda67e8b0011>:0 
>   at OverlayScreen.LateUpdate () [0x00000] in <76bf6a41bfb64def9b51dda67e8b0011>:0 
>  
> (Filename: <8aff9a85111748d8ba77255c30ac2322> Line: 0)
> 

Is this same error?

thanks!

_Originally posted by @takumiabe in https://github.com/AzeTheGreat/ONI-Mods/issues/2#issuecomment-605439640_

**Comment by AzeTheGreat** [comment]
@Takumiabe It's in a different mod so it's a different issue, but thanks for reporting this.  Can you reproduce it or does it seem to happen randomly?

**Comment by AzeTheGreat** [comment]
I was able to reproduce this on my own, it has been fixed in 5bd38ce24dd2a23e80bcf1cf4dfc507116e7ce9f.  Thanks for the report, an updated mod will be available soon.

**Comment by takumiabe** [comment]
@AzeTheGreat 
Thank you for fix! (I'm sorry not to reply rapidly...)
I wait the coming update to steam subscription :)
