### ISSUE TITLE
Endless Science - Translation

### ISSUE THREAD

**Issue by DarkEviL88** [AzeTheGreat/ONI-Mods#42]
[ru.zip](https://github.com/AzeTheGreat/ONI-Mods/files/14385226/ru.zip)

**Comment by AzeTheGreat** [comment]
Thank you.  Implemented in 79ff3e27cb9a2ffc7dcc191830d5d1909ab70c5d.

**Comment by DarkEviL88** [comment]
I think I made a translation error. The line "Science outside range" means not only that the skill "Science" may be too high, but also low. So the translation should be: "Слишком высокий или низкий навык "Наука"", for some reason I thought that the Science skill could only be too high. That's what happens when your head doesn't think clearly because of illness. I assume that I will still find some errors in the translation, I will observe as I play and then I will fix everything and share the corrected translation.
