### ISSUE TITLE
Default Buildings Settings crashes with the Ceres Beta

### ISSUE THREAD

**Issue by pixelkritzel** [AzeTheGreat/ONI-Mods#43]
Mostly an FYI Default Building Settings crashes with the current beta of the Ceres DLC when I click on settings in the mod updater.

MissingMethodException: bool DlcManager.IsContentActive(string)

PeterHan.PLib.Options.OptionsEntry.BuildOptions (System.Type forType) (at <0ae9c1a87912474b9fa3558c8a4297ce>:0)
PeterHan.PLib.Options.OptionsDialog..ctor (System.Type optionsType) (at <0ae9c1a87912474b9fa3558c8a4297ce>:0)
PeterHan.PLib.Options.POptions.Process (System.UInt32 operation, System.Object args) (at <0ae9c1a87912474b9fa3558c8a4297ce>:0)
PeterHan.PLib.Core.PRemoteComponent.Process (System.UInt32 operation, System.Object args) (at <7a2eede3e9174e45a620b79deec898e9>:0)
PeterHan.PLib.Core.PRemoteComponent.Process (System.UInt32 operation, System.Object args) (at <10ca0a7220434a67912405b6d9c79d80>:0)
PeterHan.PLib.Options.POptions+ModOptionsHandler.ShowDialog (UnityEngine.GameObject _) (at <10ca0a7220434a67912405b6d9c79d80>:0)
PeterHan.PLib.UI.PButton+<>c__DisplayClass15_0.<Build>b__0 () (at <10ca0a7220434a67912405b6d9c79d80>:0)
KButton.SignalClick (KKeyCode btn) (at /home/build/workspace/game/Assets/Plugins/Klei/ui/KButton.cs:89)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at /home/build/workspace/game/Assets/Plugins/Klei/ui/KButton.cs:130)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at /home/build/workspace/game/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at /home/build/workspace/game/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:262)
UnityEngine.EventSystems.EventSystem:Update() (at /home/build/workspace/game/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:385)

Build: U52-616718-SCD

I think SGT_Imalas had yesterday the same issue. Klei renamed the IsContentActive method

**Comment by AzeTheGreat** [comment]
I appreciate the report.  However, I don't actively support betas since they are so prone to change.  Additionally, this looks like it's probably just a crash in the POptions lib we use.  If this crash persists into release, please submit another report and I'll take a look.
