### ISSUE TITLE
[Endless Science] CTD when duplicant begins research

### ISSUE THREAD

**Issue by ManInTheMists** [AzeTheGreat/ONI-Mods#47]
When a duplicant attempts to access a researching station, the game will crash.

Player log is provided, relevant section can be skipped to by searching for "Rowan Exception in: Worker.StartWork(ResearchCenter)"

[Player.log](https://github.com/user-attachments/files/18090356/Player.log)

**Comment by AzeTheGreat** [comment]
Thanks for the report.  This should be fixed in 595dd16e2abe2c2111fc287e632ea86a799a3fc2.
