### ISSUE TITLE
Default Building Settings - Loading Time Issue

### ISSUE THREAD

**Issue by potatoesALLday** [AzeTheGreat/ONI-Mods#6]
regarding the comment on steam, my colony has at least tripple the loading time with the mod active.
i created this seed with ony's world generation manager. wonder if thats related

i really like your mod. would be cool if you'd figure out what the issue is. so i could use it again c:

cheers

---
[spacechaos deluxe.zip](https://github.com/AzeTheGreat/ONI-Mods/files/4974307/spacechaos.deluxe.zip)

**Comment by AzeTheGreat** [comment]
Thank you for the save.  I was able to find no significant difference in load times with and without Default Building Settings.  Either way took approximately 18 seconds on my setup.  Can you reproduce the load time issue with only this mod active?

**Comment by potatoesALLday** [comment]
thank you for your quick reply. i tried to checking/unchecking different mods to better pinpoint the problem and stopped the time.
i could reproduce the problem with only this mod active.

- 22sec no mods active
- 26sec all mods active except Default Building Settings Mod
- 103sec only Default Building Settings Mod active
- 121sec all mods active (29 mods in total)

**Comment by AzeTheGreat** [comment]
Strange.  What OS are you on?

**Comment by potatoesALLday** [comment]
it seems like unsubscribing/resubscribing the mod over steam workshop fixed the issue.
one interesting observation i encountered afterwards:
loading the colony suddenly gave me lots of notifications that the order of mods changed.

any idea what might have been the problem?
windows 10 btw is the os i'm running on.

**Comment by AzeTheGreat** [comment]
There was a brief period where Klei updated the game in a way that caused a change I had previously made to still work, but cause massive performance issues.  You must've had a mod version from before I updated (Steam likes to do this, I'd suggest getting Mod Updater).

Glad this is fixed now - sorry I didn't realize sooner what was probably happening.
