### ISSUE TITLE
game crash when clicking on dead bodies 

### ISSUE THREAD

**Issue by tonimark** [AzeTheGreat/ONI-Mods#7]
what happens: so somebody dies (in my case I have duplicant ageing mod and a duplicant has passed out due to their old age)
and when I click to view the body location on the menu the OPS-A-DAISY error shows up EDIT: however I located the body myself and I found out that when selecting the dead body the error shows up, 
what excepted to happen: I would see the information of the dead body what actually happened: game crash (OPS-A-DAISY screen) from your mod 
and so I reported the issue here because the error screen shows the clarified max decor mod 
ERROR DETAILS:
error.txt [this is what the OPS-A-DAISY (AKA CRASH LOG) screen shows]:[error.txt](https://github.com/AzeTheGreat/ONI-Mods/files/5012196/error.txt)
output.log:
[output_log.txt](https://github.com/AzeTheGreat/ONI-Mods/files/5012208/output_log.txt)
other notes: it can be an incompatibility with duplicant ageing mod 
how to reproduce:1.kill a duplicant
2.click on the dead body
3.see the error

**Comment by AzeTheGreat** [comment]
Thank you for the report, this has been fixed in the latest release.
