### ISSUE TITLE
Better Deselect Crashes

### ISSUE THREAD

**Issue by Tellik** [AzeTheGreat/ONI-Mods#8]
I'm getting a few random/weird crashes. The one I have logs for is when attempting to push B to copy a building added by a building.

Player Log: https://pastebin.com/0B2dHr57 and relevant part: 

`[03:47:18.606] [1] [INFO] Better Deselect's patched_method PlanScreen.OnKeyDown matched in the stack trace, adding to referenced mods list
KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at PlanScreen.CopyBuildingOrder (Building building) [0x0005f] in <fea95bc6a22241159972033b5021dc0f>:0 
  at PlanScreen.OnClickCopyBuilding () [0x00064] in <fea95bc6a22241159972033b5021dc0f>:0 
  at (wrapper dynamic-method) PlanScreen.OnKeyDown_Patch0(object,KButtonEvent)
  at KScreenManager.OnKeyDown (KButtonEvent e) [0x00036] in <fba0ad6f4fff4d9fb7364264198b41aa>:0 
  at KInputHandler.HandleKeyDown (KButtonEvent e) [0x0001c] in <fba0ad6f4fff4d9fb7364264198b41aa>:0 
  at KInputHandler.HandleKeyDown (KButtonEvent e) [0x0006f] in <fba0ad6f4fff4d9fb7364264198b41aa>:0 
  at KInputHandler.HandleEvent (KInputEvent e) [0x00008] in <fba0ad6f4fff4d9fb7364264198b41aa>:0 
  at KInputController.Dispatch () [0x0001c] in <fba0ad6f4fff4d9fb7364264198b41aa>:0 
  at KInputManager.Dispatch () [0x00017] in <fba0ad6f4fff4d9fb7364264198b41aa>:0 
  at KInputManager.Update () [0x0002e] in <fba0ad6f4fff4d9fb7364264198b41aa>:0 
  at GameInputManager.Update () [0x00007] in <fba0ad6f4fff4d9fb7364264198b41aa>:0 
  at Global.Update () [0x00000] in <fea95bc6a22241159972033b5021dc0f>:0 
 
(Filename: <e1319b7195c343e79b385cd3aa43f5dc> Line: 0)`

The second one I'm only guessing so far, but I'm suspecting it's Better Deselect with how it's happening. During the saving process, if I have a menu that's being held by Better Deselect, the game finishes saving than crashes. If it happens again or you're interested, I'll reproduce it. I've basically resorted to saving every 10 cycles and not touching the controls during a save to avoid it for now.

I do remember having a weird crash issue with this mod a while ago from when I talked to you last, so I'm going to try using that method to see if it prevents the crash in these two situations.

**Comment by AzeTheGreat** [comment]
Thanks for the reports, I’ll try to look into these.  Can you let me know exactly how you have Better Deselect configured?

**Comment by Tellik** [comment]
Originally it was on default settings, 2nd/2nd/Hold Selected. I tried switching it to Deselect Selected and it crashed on B again.

I'm going to do some more testing here (settings: 2nd/2nd/Deselect Selected) while I wake up to see how I can narrow it down a little more.

Test One: Copy Buildings with B (any/modded/vanilla), new save, vanilla map, all mods enabled, paused/any speed.
Result: No Crash

Test Two: Copy Buildings with B (any/modded/vanilla); and (Test of save crash issue, no crash)
Conditions: old save, modded map, all mods enabled, paused/any speed.
Result: Crash https://pastebin.com/EuPSc8zE

Test Three: Copy Buildings with B (any/modded/vanilla), new save, modded map, all mods enabled, paused/any speed.
Result: No Crash

Conclusion: Something is messed up with my current map I'm playing. I cannot recreate it at all under any of the conditions in a new situation, only in the original situation.

Test Four: Copy Building with B (Smart Reservoir); and (Test of save crash issue, no crash)
Conditions: old save, modded map, Better Deselect and Smart Reservoir mods only, paused/any speed.
Result: Copy Crash https://gyazo.com/c9a68e443863e918c56edce34631ac19 https://pastebin.com/xZ9JBC69

Notes: So in my original map, the only building I've seen this cause a crash so far is with Smart Reservoir's modded items. This doesn't occur in a new map under any condition. So I feel like it's somehow specific to the map/save game. But in that save, it is 100% reproducible. 

Attached Save File: [SF 2.0.sav.zip](https://github.com/AzeTheGreat/ONI-Mods/files/5453590/SF.2.0.sav.zip)

I also for the life of me can't figure out what was originally causing the crash during save. I can't recreate it at all, even switching the settings around. It happened during the early few cycle autosaves, but it's not happening now. So if I happens again, I'll update this.

I might try making a new game here shortly, and see if I can get anything recreated naturally, or just chalk it off to a corrupted map save.

**Comment by AzeTheGreat** [comment]
Testing that save, it appears to crash with just Smart Reservoirs enabled.  This appears to be an issue with Smart Reservoirs and not Better Deselect.

My guess on the second is some similar issue that's causing a crash on its own, and just appears to come from Better Deselect due to me having to touch a lot of methods in the UI.

I'm going to close this issue for now.  If you can figure out more information on crashes or find evidence that it's actually Better Deselect's fault, feel free to comment further here or open a new issue.

**Comment by Tellik** [comment]
Yeah, no worries. I really think it was just something to do with that save.

I'm 150 cycles into a different game now, and haven't seen a single hint of a problem anymore. Glad that it didn't end up being anything too rough and more of a false alarm.
