### ISSUE TITLE
[crash] Better Info Cards

### ISSUE THREAD

**Issue by coppergaga** [AzeTheGreat/ONI-Mods#9]
Hi, there:

   Your mods are very useful but `Better Info Cards` crashes sometimes.
   Any reply will be appraciated.

 Here are the logs:
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <9577ac7a62ef43179789031239ba8798>:0) System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <9577ac7a62ef43179789031239ba8798>:0) BetterInfoCards.InfoCard.<GetTextOverrides>g__GetResult|20_0 (System.Collections.Generic.List`1[T] cards, BetterInfoCards.InfoCard card, System.Int32 i) (at <e85df6d8c6e64e709f38ff29532e4b40>:0) BetterInfoCards.InfoCard+<>c__DisplayClass20_0.<GetTextOverrides>b__1 (BetterInfoCards.InfoCard x) (at <e85df6d8c6e64e709f38ff29532e4b40>:0) System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].ToList () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0) System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0) BetterInfoCards.InfoCard.GetTextOverrides (System.Collections.Generic.List`1[T] cards) (at <e85df6d8c6e64e709f38ff29532e4b40>:0) BetterInfoCards.DisplayCard..ctor (System.Collections.Generic.List`1[T] infoCards) (at <e85df6d8c6e64e709f38ff29532e4b40>:0) BetterInfoCards.DisplayCards.UpdateData (System.Collections.Generic.List`1[T] infoCards) (at <e85df6d8c6e64e709f38ff29532e4b40>:0) BetterInfoCards.CollectHoverInfo+EditWidgets_Patch.Postfix () (at <e85df6d8c6e64e709f38ff29532e4b40>:0) (wrapper dynamic-method) HoverTextDrawer.EndDrawing_Patch1(object) (wrapper dynamic-method) SelectToolHoverTextCard.UpdateHoverElements_Patch0(object,System.Collections.Generic.List`1<KSelectable>) InterfaceTool.UpdateHoverElements (System.Collections.Generic.List`1[T] hits) (at <1c58b1f98f5849baa9083bfd5185b144>:0) InterfaceTool.LateUpdate () (at <1c58b1f98f5849baa9083bfd5185b144>:0)

**Comment by coppergaga** [comment]
[output_log.txt](https://github.com/AzeTheGreat/ONI-Mods/files/5744373/output_log.txt)

**Comment by AzeTheGreat** [comment]
I suspect you have an outdated mod, that crash should be impossible now.  Please use Mod Updater to ensure you have the most recent version.

Also, unless you're on a very outdated version of the game, you should be uploading the Player.log file now, not the old output_log.txt file.  Make sure you upload it directly after a crash, before launching the game again, as doing so will overwrite the file with the new log.

The log you've uploaded doesn't contain a crash, so unfortunately I can't help any more.  I'm going to close this issue, and if you get another crash with a log feel free to add it here and I'll take a look again.

**Comment by coppergaga** [comment]
> outdated

Maybe I get a wrong log dir :( , and the log file would be correct if happens to me again. Anyhow, thanks a lot.
